site_name: LTB K8s Backend
site_description: A Kubernetes Operator and User management for the Lab Topology Builder.
site_author: Jan Untersander, Tsigereda Nebai Kidane
site_url: https://lab-topology-builder.github.io/LTB-K8s-Backend/
repo_name: Lab-Topology-Builder/LTB-K8s-Backend
repo_url: https://github.com/Lab-Topology-Builder/LTB-K8s-Backend/
copyright: Copyright &copy; 2023 Jan Untersander, Tsigereda Nebai Kidane

nav:
  - Home: README.md
  - User Guide: user-guide.md
  - Concepts: concepts.md
  - Contributions:
    - Contributor Guide: contributions/contributor-guide.md
    - Coding Conventions: contributions/coding-conventions.md
    - Development Cluster Setup: contributions/dev-cluster-setup.md
    - Tools and Frameworks: contributions/technologies-used.md
    - Testing: contributions/test-concepts.md
    - Continuous Integration: contributions/ci.md
  - ...
  - Comparison: comparison.md
  - About: about.md
plugins:
  - search
  - awesome-pages:
  - exclude:
      glob:
        - decisions/adr-template.md
        - decisions/README.md
  - glightbox
  - print-site
  # - git-authors
  # - git-revision-date-localized:
  #     fallback_to_build_date: true
  # - git-committers:
  #     repository: Lab-Topology-Builder/LTB-Kubernetes-Operator
  #     branch: main
  # - social
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - doc-includes/glossary.md
  - pymdownx.tasklist:
      custom_checkbox: false
theme:
  name: material
  logo: assets/images/LTB_Text_RGB.svg
  favicon: assets/images/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    # - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - search.highlight
    - search.suggest
    - content.action.edit
    - content.code.copy
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
# copyright: Copyright &copy; 2023 Jan Untersander, Tsigereda Nebai Kidane
edit_uri: blob/main/docs/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lab-Topology-Builder/LTB-K8s-Backend
