
- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
	- custom-scorecard-tests
	- customtest
	image: quay.io/operator-framework/custom-scorecard-tests:dev
	labels:
		suite: custom
		test: customtest
