apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ltb-backend.ltb/v1alpha1",
          "kind": "LabInstance",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "operator",
              "app.kubernetes.io/instance": "labinstance-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "labinstance",
              "app.kubernetes.io/part-of": "operator"
            },
            "name": "labinstance-sample"
          },
          "spec": {
            "labTemplateReference": "labtemplate-sample"
          }
        },
        {
          "apiVersion": "ltb-backend.ltb/v1alpha1",
          "kind": "LabInstanceSet",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "operator",
              "app.kubernetes.io/instance": "labinstanceset-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "labinstanceset",
              "app.kubernetes.io/part-of": "operator"
            },
            "name": "labinstanceset-sample"
          },
          "spec": {
            "generator": {
              "labInstances": [
                {
                  "name": "labInstance1"
                },
                {
                  "name": "labInstance2"
                }
              ]
            }
          }
        },
        {
          "apiVersion": "ltb-backend.ltb/v1alpha1",
          "kind": "LabTemplate",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "operator",
              "app.kubernetes.io/instance": "labtemplate-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "labtemplate",
              "app.kubernetes.io/part-of": "operator"
            },
            "name": "labtemplate-sample"
          },
          "spec": {
            "neighbors": [
              "TestHost1:1,TestHost2:1",
              "TestHost1:2,TestHost3:1"
            ],
            "nodes": [
              {
                "config": "#cloud-config\npassword: ubuntu\nchpasswd: { expire: False }\nssh_pwauth: True\npackages:\n  - qemu-guest-agent\nruncmd:\n  - [ systemctl, start, qemu-guest-agent ]",
                "name": "sample-node-1",
                "nodetyperef": {
                  "image": "ubuntu",
                  "type": "nodetypeubuntuvm",
                  "version": "22.04"
                },
                "ports": [
                  {
                    "name": "ssh",
                    "port": 22,
                    "protocol": "TCP"
                  }
                ]
              },
              {
                "name": "sample-node-2",
                "nodetyperef": {
                  "image": "ghcr.io/insrapperswil/network-ninja",
                  "type": "genericpod",
                  "version": "latest"
                },
                "ports": [
                  {
                    "name": "ssh",
                    "port": 22,
                    "protocol": "TCP"
                  }
                ]
              },
              {
                "name": "sample-node-3",
                "nodetyperef": {
                  "image": "ubuntu",
                  "type": "genericpod",
                  "version": "22.04"
                },
                "ports": [
                  {
                    "name": "ssh",
                    "port": 22,
                    "protocol": "TCP"
                  }
                ]
              }
            ]
          }
        },
        {
          "apiVersion": "ltb-backend.ltb/v1alpha1",
          "kind": "NodeType",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "operator",
              "app.kubernetes.io/instance": "nodetype-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "nodetype",
              "app.kubernetes.io/part-of": "operator"
            },
            "name": "genericpod"
          },
          "spec": {
            "kind": "pod",
            "nodeSpec": "containers:\n  - name: {{ .Name }}\n    image: {{ .NodeTypeRef.Image}}:{{ .NodeTypeRef.Version }}\n    command: [\"/bin/bash\", \"-c\", \"apt update \u0026\u0026 apt install -y openssh-server \u0026\u0026 service ssh start \u0026\u0026 sleep 365d\"]\n    ports:\n      {{- range $index, $port := .Ports }}\n      - name: {{ $port.Name }}\n        containerPort: {{ $port.Port }}\n        protocol: {{ $port.Protocol }}\n      {{- end }}\n"
          }
        },
        {
          "apiVersion": "ltb-backend.ltb/v1alpha1",
          "kind": "NodeType",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "operator",
              "app.kubernetes.io/instance": "nodetype-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "nodetype",
              "app.kubernetes.io/part-of": "operator"
            },
            "name": "nodetypeubuntuvm"
          },
          "spec": {
            "kind": "vm",
            "nodeSpec": "running: true\ntemplate:\n  spec:\n    domain:\n      resources:\n        requests:\n          memory: 4096M\n      cpu:\n        cores: 2\n      devices:\n        disks:\n          - name: containerdisk\n            disk:\n              bus: virtio\n    terminationGracePeriodSeconds: 0\n    volumes:\n      - name: containerdisk\n        containerDisk:\n          image: quay.io/containerdisks/ubuntu:22.04\n"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-05-19T17:24:13Z"
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - displayName: Lab Instance
      kind: LabInstance
      name: labinstances.ltb-backend.ltb
      version: v1alpha1
    - displayName: Lab Instance Set
      kind: LabInstanceSet
      name: labinstancesets.ltb-backend.ltb
      version: v1alpha1
    - displayName: Lab Template
      kind: LabTemplate
      name: labtemplates.ltb-backend.ltb
      version: v1alpha1
    - description: NodeType is the Schema for the nodetypes API
      displayName: Node Type
      kind: NodeType
      name: nodetypes.ltb-backend.ltb
      version: v1alpha1
  description: LTB
  displayName: LTB-Backend
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstances/finalizers
          verbs:
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstancesets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstancesets/finalizers
          verbs:
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labinstancesets/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labtemplates
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labtemplates/finalizers
          verbs:
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - labtemplates/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - nodetypes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - nodetypes/finalizers
          verbs:
          - update
        - apiGroups:
          - ltb-backend.ltb
          resources:
          - nodetypes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: operator
          control-plane: controller-manager
        name: operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/lab-topology-builder/ltb-k8s-backend:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - LTB
  links:
  - name: Operator
    url: https://operator.domain
  maintainers:
  - email: jan.untersander@ost.ch
    name: Jan Untersander
  maturity: alpha
  provider:
    name: LTB
  version: 0.0.1
