# permissions for end users to edit nodetypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodetype-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: nodetype-editor-role
rules:
- apiGroups:
  - ltb-backend.ltb
  resources:
  - nodetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ltb-backend.ltb
  resources:
  - nodetypes/status
  verbs:
  - get
