---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pods/status
  verbs:
  - get
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachines/status
  verbs:
  - get
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstances/finalizers
  verbs:
  - update
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstancesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstancesets/finalizers
  verbs:
  - update
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labinstancesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labtemplates/finalizers
  verbs:
  - update
- apiGroups:
  - ltb-backend.ltb
  resources:
  - labtemplates/status
  verbs:
  - get
  - patch
  - update
