apiVersion: ltb-backend.ltb/v1alpha1
kind: NodeType
metadata:
  labels:
    app.kubernetes.io/name: nodetype
    app.kubernetes.io/instance: nodetype-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: nodetypeubuntuvm
spec:
  kind: vm
  nodeSpec: |
    running: true
    template:
      spec:
        domain:
          resources:
            requests:
              memory: 4096M
          cpu:
            cores: 2
          devices:
            disks:
              - name: containerdisk
                disk:
                  bus: virtio
              - name: cloudinitdisk
                disk:
                  bus: virtio
            interfaces:
              - name: default
                bridge: {}
              - name: labNetwork
                bridge: {}
        terminationGracePeriodSeconds: 0
        volumes:
          - name: containerdisk
            containerDisk:
              image: quay.io/containerdisks/ubuntu:22.04
          - name: cloudinitdisk
            cloudInitNoCloud:
              userData: |
                #cloud-config
                hostname: ltbtestvm
        networks:
          - name: default
            pod: {}
          - name: labNetwork
            multus:
              networkName: labNetwork

---

apiVersion: ltb-backend.ltb/v1alpha1
kind: NodeType
metadata:
  labels:
    app.kubernetes.io/name: nodetype
    app.kubernetes.io/instance: nodetype-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: genereicpod
spec:
  kind: pod
  nodeSpec: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: testnodetypepod
    spec:
      containers:
        - name: "testcontainer"
          image: ubuntu:latest
