apiVersion: ltb-backend.ltb/v1alpha1
kind: LabTemplate
metadata:
  labels:
    app.kubernetes.io/name: labtemplate
    app.kubernetes.io/instance: labtemplate-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: labtemplate-sample
spec:
  nodes:
  - name: "sample-node-1"
    nodetyperef:
      type: "nodetypeubuntuvm"
      image: "ubuntu"
      version: "22.04"
    config: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
              ssh_pwauth: True
              packages:
                - qemu-guest-agent
              runcmd:
                - [ systemctl, start, qemu-guest-agent ]
    ports:
    - name: "ssh"
      port: 22
      protocol: "TCP"
  - name: "sample-node-2"
    nodetyperef:
      type: "genericpod"
      image: "ghcr.io/insrapperswil/network-ninja"
      version: "latest"
    ports:
    - name: "ssh"
      port: 22
      protocol: "TCP"
  - name: "sample-node-3"
    nodetyperef:
      type: "genericpod"
      image: "ubuntu"
      version: "22.04"
    ports:
    - name: "ssh"
      port: 22
      protocol: "TCP"
  connections:
  - "TestHost1:1,TestHost2:1"
  - "TestHost1:2,TestHost3:1"
