apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
    name: macvlan-conf-1
spec:
    config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                        "subnet": "10.10.0.0/24",
                        "rangeStart": "10.10.0.10",
                        "rangeEnd": "10.10.0.250"
                    } ]
                ]
            }
        }'
