apiVersion: v1
kind: Service
metadata:
  name: remote-access
  labels:
    app: remote-access
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
      targetPort: 22
  selector:
    app: remote-access
