# Most of the data need to be checked
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: labinstancesets.github.com/lab-topology-builder
spec:
  group: lab-topology-builder #/apis/group/version
  names:
    kind: LabInstanceSet # need to check this
    listKind: LabInstanceSetList
    plural: labinstancesets
    singular: labinstanceset
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            generators:
            list:
              properties:
                elements:
                  items:
                    x-kubernetes-preserve-unknown-fields: true
                  type: array
            template:
              properties:
                metadata:
                  properties:
                    labels:
                      type: object
                    name:
                      type: string
                    namespace:
                      type: string
                  type: object
                spec:
                  properties:
                    hosts:
                      items:
                        properties:
                          name:
                            type: string
                          image:
                            properties:
                              type:
                                type: string
                              version:
                                type: string
                            type: object
                          interfaces:
                            items:
                              properties:
                                connects:
                                  items:
                                    properties:
                                      name:
                                        type: string
                                      tag:
                                        type: string
                                      ipv6:
                                        type: string
                                      ipv4:
                                        type: string
                                      mac:
                                        type: string
                                    type: object
                                  type: array
                              type: object
                            type: array
                          config:
                            type: string
                        type: object
                      type: array
                  type: object

