# Most of the data need to be checked
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "ltboperators.github.com/lab-topology-builder"
spec:
  group: lab-topology-builder #/apis/group/version
  names:
    kind: LTBOperator # need to check this
    listKind: LTBOperatorList
    plural: ltboperators
    singular: ltboperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: string
          spec:
            type: object
            properties:
              labInstanceSet:
                properties:
                  env:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                    valueFrom:
                      properties:
                        configMapKeyRef:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                      type: object
                    fieldRef:
                      properties:
                        apiVersion:
                          type: string
                        fieldPath:
                          type: string
                      type: object
                    resourceFieldRef:
                      properties:
                        containerName:
                          type: string
                      type: object
                    secretKeyRef:
                      properties:
                        key:
                          type: string
                        name:
                          type: string
                      type: object
                type: object
