apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: lab-topology-builder-catalog
  namespace: operators
spec:
  displayName: LTB Operator
  image: ghcr.io/lab-topology-builder/ltb-k8s-backend-catalog:v0.0.1
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 45m
