apiVersion: ltb-backend.ltb/v1alpha1
kind: LabTemplate
metadata:
  labels:
    app.kubernetes.io/name: labtemplate
    app.kubernetes.io/instance: labtemplate-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: labtemplate-sample
spec:
  template:
    name: "labtemplate-sample"
    spec:
      hosts:
      - name: "sample-host-1"
        image:
          type: "ubuntu"
          version: "latest"
      - name: "sample-host-2"
        image:
          type: "ubuntu"
          version: "latest"
