name: deploy-docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: squidfunk/mkdocs-material:9.0.13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: true
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: git config --global --add safe.directory /__w/LTB-K8s-Backend/LTB-K8s-Backend
      - run: pip install mkdocs-material mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 pillow cairosvg mkdocs-glightbox mkdocs-print-site-plugin mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
