name: deploy-docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: squidfunk/mkdocs-material:9.0.13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: true
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: git config --global --add safe.directory /__w/LTB-K8s-Backend/LTB-K8s-Backend
      # Install Go
      - uses : actions/setup-go@v2
        with:
          go-version: 1.20
      # Install crd-ref-docs for generating API reference docs
      - run: go install github.com/elastic/crd-ref-docs@v0.0.9
      # Install mkdocs and plugins
      - run: pip install mkdocs-material mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 pillow cairosvg mkdocs-glightbox mkdocs-material pymdown-extensions mkdocs-exclude mkdocstrings[crystal,python] mkdocs-monorepo-plugin mkdocs-print-site-plugin mkdocs-awesome-pages-plugin
      # Generate API reference docs
      - run: make generate-crd-docs
      # Build the site
      - run: mkdocs gh-deploy --force
